name: Evidence Binding

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    uses: Quirk-Systems/.github/.github/workflows/reusable-evidence-binding.yml@ed2f2ff7caacdb7a148ac9811dce1e7cce48a7c8 # main 2026-10-04
